# Custom Language File for Launcher Customizer

[ejs.app]
title = "EpsyCraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Timortal0/EpsyCraftLauncher"
mediaTwitterURL = "https://x.com/timortall"
mediaInstagramURL = "https://www.twitch.tv/timortal"
mediaYouTubeURL = "https://www.twitch.tv/timortal"
mediaDiscordURL = "https://discord.gg/wDAcxbuR9U"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR EPSYCRAFT"
welcomeDescription = "Ceci est une version en cours de développement - merci de ne pas publier le contenu de la MAJ"
welcomeDescCTA = "L'aventure va bientôt commencer !"
