[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Pseudo"
usernameEditButton = "Edit"
settingsTooltip = "Options"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "MOJANG STATUS"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essential"
newsButton = "NEWS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actus.."
newsErrorFailedSpan = "Impossible de charger les actus"
newsErrorRetryButton = "Réessayez"
newsErrorNoneSpan = "Pas d'actus !"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Erreur"
loginEmailPlaceholder = "MAIL OU IDENTIFIANT"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "POV : tu as oublié ton mot de passe?"
loginRememberMeText = "Rester connecté?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte?"
loginPasswordDisclaimer1 = "Votre mot de passe est directement envoyé à Mojang et n'est jamais sauvegardé."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié avec Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Connexion avec Microsoft"
loginWithMojang = "Connexion avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponible"
serverSelectConfirm = "Choisir"
serverSelectCancel = "Annuler"
accountSelectHeader = "Choisir un compte"
accountSelectConfirm = "Choisir"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Options"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "A propos"
navUpdates = "Mise à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramétre du compte"
tabAccountHeaderDesc = "Ajouter un compte ou en modifier un."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Options de Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution en jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Connexion automatique à Epsycraft."
launchDetachedTitle = "Launch game process detached from launcher."
launchDetachedDesc = "If the game is not detached, closing the launcher will also close the game."
tabModsHeaderText = "Options des mods"
tabModsHeaderDesc = "Activé ou désactivé un mod"
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Drop-in Mods"
addMods = "Ajouter un mod"
dropinRefreshNote = "(F5 pour refresh)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Ajouter ou modifier un shaderpack. Cela affecte vos performances en jeu."
selectShaderpack = "Sélectionner le Shaderpack"
tabJavaHeaderText = "Options Java"
tabJavaHeaderDesc = "Modifier la configuration Java (advanced)."
memoryTitle = "MMémoire"
maxRAM = "RAM maximum"
minRAM = "RAM minimum"
memoryDesc = "La RAM recommandé est 3Go. Modifier la RAM peut réduire le LAG."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécuteur Java"
javaExecSelButtonText = "Choisir les fichiers"
javaExecDesc = "L'exécuteur Java est validé avant le lancement du jeu."
javaPathDesc = "The path should end with <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Additional JVM Options"
jvmOptsDesc = "Options to be provided to the JVM at runtime. <em>-Xms</em> and <em>-Xmx</em> should not be included."
launcherTabHeaderText = "Options du Launcher"
launcherTabHeaderDesc = "Options relatif au launcher lui-même."
allowPrereleaseTitle = "Autorisé les pré-mise à jour."
allowPrereleaseDesc = "Les pré-mise à jour peuvent inclure du contenu qui peut ne pas être stable et amener des performances aléatoires."
dataDirectoryTitle = "Data Directory"
selectDataDirectory = "Select Data Directory"
chooseFolder = "Chosir un dossier"
dataDirectoryDesc = "All game files and local Java installations will be stored in the data directory.<br>Screenshots and world saves are stored in the instance folder for the corresponding server configuration."
aboutTabHeaderText = "A propos"
aboutTabHeaderDesc = "View information and release notes for the current version."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Source (GitHub)"
support = "Support"
devToolsConsole = "DevTools Console"
releaseNotes = "Notes de version"
changelog = "Changelog"
noReleaseNotes = "Pas de notes de version"
viewReleaseNotes = "Voir les notes de version sur GitHub"
launcherUpdatesHeaderText = "Mise à jour du launcher"
launcherUpdatesHeaderDesc = "Download, install, and review updates for the launcher."
checkForUpdates = "Recherche une mise à jour"
whatsNew = "Quoi de neuf ici ?"
updateReleaseNotes = "Mise à jour de la note de version"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"


[js.discord]
waiting = "En attente du Client.."
state = "Serveur: {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "SE CONNEXTER"
success = "SUCCES"
tryAgain = "Réessayez"

[js.login.error]
invalidValue = "* valeur invalides"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue pendant la connexion"
desc = "Une erreur est survenue. Merci de consulter la console pour plus d'infos."

[js.landing.launch]
pleaseWait = "Merci de patienter.."
failureTitle = "Erreur pendant le lancement"
failureText = "Voir la console (CTRL + Shift + i) pour plus d'infos."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "Hors ligne"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des infos système.."
noCompatibleJava = "Pas d'installation<br>Java trouvé"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une version 64-bit de Java {major}. Voulez-vous l'installer?"
installJava = "Installer Java"
installJavaManually = "Installer Java Manuellement"
javaDownloadPrepare = "Préparation de l'instalation de Java.."
javaDownloadFailureTitle = "Erreur pendant l'installation de Java"
javaDownloadFailureText = "Voir la console (CTRL + Shift + i) pour plus d'infos."
javaRequired = "Java est requis<br> pour lancer"
javaRequiredMessage = 'A valid x64 installation of Java {major} is required to launch.<br><br>Please refer to our <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Java Management Guide</a> for instructions on how to manually install Java.'
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver OpenJDK distribution."
javaDownloadCorruptedError = "Le téléchargement de JDK à rencontré un problème"
extractingJava = "Extraction de Java"
javaInstalled = "Java est bien installé !"

[js.landing.dlAsync]
loadingServerInfo = "Information serveur en cours.."
fatalError = "Erreur fatal"
unableToLoadDistributionIndex = "Could not load a copy of the distribution index. See the console (CTRL + Shift + i) for more details."
pleaseWait = "Merci de patienter.."
errorDuringLaunchTitle = "Erreur pendant le lancement"
seeConsoleForDetails = "Voir la console (CTRL + Shift + i) pour plus d'information."
validatingFileIntegrity = "Vérification des fichiers en cours.."
errorDuringFileVerificationTitle = "Erreur pendant la vérification"
downloadingFiles = "Téléchargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur pendant le téléchargement des fichiers"
preparingToLaunch = "Préparation au lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
doneEnjoyServer = "Terminé, amusez-vous bien!"
checkConsoleForDetails = "Merci de voir la console (CTRL + Shift + i) pour plus d'infos."

[js.landing.news]
checking = "Recherche d'actus"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "Naviguer vers Epsycraft!"
joined = "Explorer Epsycraft!"

[js.overlay]
dismiss = "Rejeter"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Quelque chose ne marche pas"
errorMessage = "L'authentification Microsoft à échoué. Merci de réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Quelque chose ne marche pas"
errorMessage = "La déconnexion Microsoft à échoué. Merci de réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Choisir un compte"
selectedButton = "Compte choisit &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>Ceci est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le launcher vous devez être connecté à UN compte. Il faudra vous reconnecter.<br><br>Vous êtes sur de vouloir déconnecter ?"
confirmButton = "Je suis sûr !"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Choisir un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Déconnexion"

[js.settings.dropinMods]
removeButton = "Retirer"
deleteFailedTitle = "Impossible de supprimer<br>le mod : {fullName}"
deleteFailedMessage = "Vérifiez que le fichier n'est pas utilisé autre part."
failedToggleTitle = "Failed to Toggle<br>One or More Drop-in Mods"
okButton = "Okey"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Selected: Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Java {major} x64 requis."
availableOptions = "Option disponible pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pre-release"
stableReleaseTitle = "Stable Release"
releaseNotesFailed = "Failed to load release notes."

[js.settings.updates]
newReleaseTitle = "New Release Available"
newPreReleaseTitle = "New Pre-release Available"
downloadingButton = "Downloading.."
downloadButton = 'Download from GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Close the launcher and run the dmg to update.</span>'
latestVersionTitle = "You Are Running the Latest Version"
checkForUpdatesButton = "Check for Updates"
checkingForUpdatesButton = "Checking for Updates.."

[js.settings.msftLogin]
errorTitle = "Microsoft Login Failed"
errorMessage = "We were unable to authenticate your Microsoft account. Please try again."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Fatal Error: Unable to Load Distribution Index"
fatalErrorMessage = "A connection could not be established to our servers to download the distribution index. No local copies were available to load. <br><br>The distribution index is an essential file which provides the latest server information. The launcher is unable to start without it. Ensure you are connected to the internet and relaunch the application."
closeButton = "Close"

[js.uibinder.validateAccount]
failedMessageTitle = "Failed to Refresh Login"
failedMessage = "We were unable to refresh the login for <strong>{account}</strong>. Please select another account or login again."
failedMessageSelectAnotherAccount = "We were unable to refresh the login for <strong>{account}</strong>. Please login again."
loginButton = "Login"
selectAnotherAccountButton = "Select Another Account"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier s'il y a des mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Error During Login:<br>Profile Not Set Up"
noProfileDesc = "Your Microsoft account does not yet have a Minecraft profile set up. If you have recently purchased the game or redeemed it through Xbox Game Pass, you have to set up your profile on <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>If you have not yet purchased the game, you can also do that on <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error During Login:<br>No Xbox Account"
noXboxAccountDesc = "Your Microsoft account has no Xbox account associated with it."
xblBannedTitle = "Error During Login:<br>Xbox Live Unavailable"
xblBannedDesc = "Your Microsoft account is from a country where Xbox Live is not available or banned."
under18Title = "Error During Login:<br>Parental Approval Required"
under18Desc = "Accounts for users under the age of 18 must be added to a Family by an adult."
unknownTitle = "Unknown Error During Login"
unknownDesc = "An unknown error has occurred. Please see the console for details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Internal Error:<br>Method Not Allowed"
methodNotAllowedDesc = "Method not allowed. Please report this error."
notFoundTitle = "Internal Error:<br>Not Found"
notFoundDesc = "The authentication endpoint was not found. Please report this issue."
accountMigratedTitle = "Error During Login:<br>Account Migrated"
accountMigratedDesc = "You've attempted to login with a migrated account. Try again using the account email as the username."
invalidCredentialsTitle = "Error During Login:<br>Invalid Credentials"
invalidCredentialsDesc = "The email or password you've entered is incorrect. Please try again."
tooManyAttemptsTitle = "Error During Login:<br>Too Many Attempts"
tooManyAttemptsDesc = "There have been too many login attempts with this account recently. Please try again later."
invalidTokenTitle = "Error During Login:<br>Invalid Token"
invalidTokenDesc = "The provided access token is invalid."
tokenHasProfileTitle = "Error During Login:<br>Token Has Profile"
tokenHasProfileDesc = "Access token already has a profile assigned. Selecting profiles is not implemented yet."
credentialsMissingTitle = "Error During Login:<br>Credentials Missing"
credentialsMissingDesc = "Username/password was not submitted or password is less than 3 characters."
invalidSaltVersionTitle = "Error During Login:<br>Invalid Salt Version"
invalidSaltVersionDesc = "Invalid salt version."
unsupportedMediaTypeTitle = "Internal Error:<br>Unsupported Media Type"
unsupportedMediaTypeDesc = "Unsupported media type. Please report this error."
accountGoneTitle = "Error During Login:<br>Account Migrated"
accountGoneDesc = "Account has been migrated to a Microsoft account. Please log in with Microsoft."
unreachableTitle = "Error During Login:<br>Unreachable"
unreachableDesc = "Unable to reach the authentication servers. Ensure that they are online and you are connected to the internet."
gameNotPurchasedTitle = "Error During Login:<br>Game Not Purchased"
gameNotPurchasedDesc = "The account you are trying to login with has not purchased a copy of Minecraft. You may purchase a copy on <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Unknown Error During Login"
unknownErrorDesc = "An unknown error has occurred. Please see the console for details."
